import {LanguageCode} from 'paperback-extensions-common'

export const reverseLangCode: {[x: string]: LanguageCode} = {
    '_unknown': LanguageCode.UNKNOWN,
    'bd': LanguageCode.BENGALI,
    'bg': LanguageCode.BULGARIAN,
    'br': LanguageCode.BRAZILIAN,
    'cn': LanguageCode.CHINEESE,
    'cz': LanguageCode.CZECH,
    'de': LanguageCode.GERMAN,
    'dk': LanguageCode.DANISH,
    'gb': LanguageCode.ENGLISH,
    'en': LanguageCode.ENGLISH,             // en is accepted by Komga
    'es': LanguageCode.SPANISH,
    'fi': LanguageCode.FINNISH,
    'fr': LanguageCode.FRENCH,
    'gr': LanguageCode.GREEK,
    'hk': LanguageCode.CHINEESE_HONGKONG,
    'hu': LanguageCode.HUNGARIAN,
    'id': LanguageCode.INDONESIAN,
    'il': LanguageCode.ISRELI,
    'in': LanguageCode.INDIAN,
    'ir': LanguageCode.IRAN,
    'it': LanguageCode.ITALIAN,
    'jp': LanguageCode.JAPANESE,
    'kr': LanguageCode.KOREAN,
    'lt': LanguageCode.LITHUANIAN,
    'mn': LanguageCode.MONGOLIAN,
    'mx': LanguageCode.MEXIAN,
    'my': LanguageCode.MALAY,
    'nl': LanguageCode.DUTCH,
    'no': LanguageCode.NORWEGIAN,
    'ph': LanguageCode.PHILIPPINE,
    'pl': LanguageCode.POLISH,
    'pt': LanguageCode.PORTUGUESE,
    'ro': LanguageCode.ROMANIAN,
    'ru': LanguageCode.RUSSIAN,
    'sa': LanguageCode.SANSKRIT,
    'si': LanguageCode.SAMI,
    'th': LanguageCode.THAI,
    'tr': LanguageCode.TURKISH,
    'ua': LanguageCode.UKRAINIAN,
    'vn': LanguageCode.VIETNAMESE
}